# Generated by Django 5.1 on 2024-08-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custom',
            name='s_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custom',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
