[compose-mysql-db] # 커넥션 이름
dialect = "mysql" # 접속할 데이터베이스 종류
username = "urstory" # 접속할 데이터베이스 계정
password = "u1234" # 접속할 데이터베이스 비밀번호
host = "localhost" # 접속할 데이터베이스 주소
database = "examplesdb" # 접속할 데이터베이스 이름