# 커넥션 이름
[connections.mydb] 
# 접속할 데이터베이스 종류
dialect = "mysql" 
# 접속할 데이터베이스 계정
username = "urstory"    
# 접속할 데이터베이스 비밀번호
password = "u1234" 
# 접속할 데이터베이스 주소 
# 호스트 이름으로 container_name을 사용함으로써, ip 변화에 대응할 수 있도록 함
host = "compose-mysql-db" 
# 접속할 mysql 내부 데이터베이스 이름
database = "examplesdb" 