# 1. Node.js 이미지를 베이스로 사용
FROM node:18

# 2. 컨테이너 내 작업 디렉토리를 설정
WORKDIR /usr/src/app

# 3. package.json과 package-lock.json 복사
COPY package*.json ./

# 4. 종속성 설치
RUN npm install

# 5. React 애플리케이션 코드를 컨테이너에 복사
COPY . .

# 6. 빌드 React 앱 (개발 환경은 빌드하지 않음)
RUN npm run build

# 7. React 앱을 실행하는 간단한 HTTP 서버 설치
RUN npm install -g serve

# 8. 애플리케이션 실행
CMD ["serve", "-s", "build"]

# 9. 컨테이너가 사용하는 포트 설정
EXPOSE 3000
