# Generated by Django 5.1 on 2024-08-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mysql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.IntegerField(unique=True)),
                ('user', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
