FROM ubuntu:18.04 

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y dist-upgrade && \
    apt-get install -y python3-pip 
# 리눅스에서 파이썬 다운받는 방법 

RUN apt update && apt -y install locales && locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN pip3 install --upgrade pip && \
    pip3 install pandas PyMySQL streamlit
# requirement.txt가 있으니 뺀다.

# COPY requirements.txt /root/
COPY main.py /root/ 
WORKDIR /root
# RUN pip3 install -r requirements.txt
EXPOSE 8080
CMD ["python3", "main.py"]


# FROM python

# WORKDIR /root/

# EXPOSE 3306:3306

# CMD [ "streamlit", "run", "streamlit.py" ]