# base image
FROM python:3.10-slim

# os 업데이트 & 설치 
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

# pip 업그레이드 추가
RUN pip install --upgrade pip
    
# 코드 복사 
COPY ./openai_chatbot /app
COPY ./requirements.txt /app

# 실행 폴더 정의 
WORKDIR /app

# 필요한 라이브러리 설치  
RUN pip3 install -r ./requirements.txt

# 실행 포트 정의 
EXPOSE 8502
# 컨테이너 실행 유무 확인 
HEALTHCHECK CMD curl --fail http://localhost:8502/_stcore/health
# 웹서버 실행 
ENTRYPOINT ["streamlit", "run", "llm_model.py", "--server.port=8502", "--server.address=0.0.0.0"]
