# Generated by Django 5.0.8 on 2024-08-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todo',
        ),
    ]
